### ISSUE TITLE
URGENT - Training Error

### ISSUE THREAD

**Issue by drisspg** [matthewdouglas/NeurIPS-LLM-Challenge-2023#1]
@matthewdouglas 

Hey so training the first model based off `sft-v0.yml ` worked as expected, but there is an error while trying to run
`accelerate launch -m axolotl.cli.train sft-v1.yml`
``` Shell
Completed!!! Saving pre-trained model to ./out/Mistral-7B-sft-v0
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/local/lib/python3.10/dist-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
                              dP            dP   dP 
                              88            88   88 
   .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88 
   88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88 
   88.  .88  .d88b.  88.  .88 88 88.  .88   88   88 
   `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP 
                                                    
                                                    

[2023-11-16 04:36:01,710] [WARNING] [axolotl.validate_config:169] [PID:2017] [RANK:0] eval_batch_size != micro_batch_size. This can lead to VRAM instability.
[2023-11-16 04:36:01,798] [INFO] [axolotl.normalize_config:128] [PID:2017] [RANK:0] GPU memory usage baseline: 0.000GB (+0.441GB misc)
[2023-11-16 04:36:01,888] [DEBUG] [axolotl.load_tokenizer:75] [PID:2017] [RANK:0] EOS: 2 / </s>
[2023-11-16 04:36:01,888] [DEBUG] [axolotl.load_tokenizer:76] [PID:2017] [RANK:0] BOS: 1 / <s>
[2023-11-16 04:36:01,888] [DEBUG] [axolotl.load_tokenizer:77] [PID:2017] [RANK:0] PAD: 2 / </s>
[2023-11-16 04:36:01,888] [DEBUG] [axolotl.load_tokenizer:78] [PID:2017] [RANK:0] UNK: 0 / <unk>
[2023-11-16 04:36:02,004] [INFO] [axolotl.load_tokenized_prepared_datasets:130] [PID:2017] [RANK:0] Unable to find prepared dataset in last_run_prepared/7a2b12504d7d2c2c3400e52c7031f252
[2023-11-16 04:36:02,004] [INFO] [axolotl.load_tokenized_prepared_datasets:131] [PID:2017] [RANK:0] Loading raw datasets...
[2023-11-16 04:36:02,004] [INFO] [axolotl.load_tokenized_prepared_datasets:136] [PID:2017] [RANK:0] No seed provided, using default seed of 42
Downloading data files: 100%|██████████| 2/2 [00:00<00:00, 19418.07it/s]
Extracting data files: 100%|██████████| 2/2 [00:00<00:00, 2437.84it/s]
Generating train split: 1 examples [00:00, 485.45 examples/s]
Generating test split: 1 examples [00:00, 1015.32 examples/s]
Map:   0%|          | 0/1 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 51, in <module>
    fire.Fire(do_cli)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 44, in do_cli
    dataset_meta = load_datasets(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/workspace/axolotl/src/axolotl/cli/__init__.py", line 225, in load_datasets
    train_dataset, eval_dataset, total_num_steps = prepare_dataset(cfg, tokenizer)
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 60, in prepare_dataset
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 484, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 269, in load_tokenized_prepared_datasets
    ds_wrapper = TokenizedPromptDataset(ds_strategy, ds)
  File "/workspace/axolotl/src/axolotl/datasets.py", line 36, in __init__
    super().__init__(self.process(dataset).data, **kwargs)
  File "/workspace/axolotl/src/axolotl/datasets.py", line 45, in process
    return dataset.map(
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/workspace/axolotl/src/axolotl/prompt_strategies/alpaca_w_system.py", line 30, in tokenize_prompt
    ) = self.parse_instruction_fields(prompt)
  File "/workspace/axolotl/src/axolotl/prompt_strategies/user_defined.py", line 57, in parse_instruction_fields
    prompt[field_instruction],
  File "/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py", line 270, in __getitem__
    value = self.data[key]
KeyError: 'prompt'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', 'sft-v1.yml']' returned non-zero exit status 1.

```

Also from looking at the highest scoring submission it appears like this is the artifact used for this submission

**Comment by matthewdouglas** [comment]
Thanks @drisspg! I'm fixing this now and changing the order so `sft-v1` is produced first. This is used in both `inference` and `inference3`. Since `inference` scored higher on the open evaluation, I think I would still like to go with that one if I can instead of `inference3`.

Repo should be updated within the hour.

**Comment by drisspg** [comment]
Can you give me write access to the repro, I would like to create a branch pointing to the newly trained artifacts

**Comment by matthewdouglas** [comment]
@drisspg Invite sent!
